# Esta version sale de frontend/Dockerfile
FROM node:22-alpine AS build

# Establece /app como carpeta de trabajo dentro de la imagen
WORKDIR /app

# Copia dentro de app package.json y package-lock
COPY package.json package-lock.json ./

# Instala las dependencias de package-lock.json
RUN npm ci

# Copia el resto del código del frontend dentro de app
COPY . .

# Dirección que utilizará el frontend para llamar a la API
ARG VITE_API_URL=/api
ENV VITE_API_URL=$VITE_API_URL

# Construye el frontend y genera la carpeta /app/dist
RUN npm run build

# Inicia una  nueva etapa utilizando otra imagen, es una imagen preparada para ejcutarse sin permisos de admin.
FROM nginxinc/nginx-unprivileged:alpine3.22 AS runner

# Copia la configuración que va a utilizar Nginx
COPY nginx.conf /etc/nginx/nginx.conf

# Copia el resultado de la etapa build a la carpeta pública de Nginx
COPY --chown=nginx:nginx --from=build /app/dist /usr/share/nginx/html

# Ejecuta Nginx con un usuario sin privilegios
USER nginx

# Puerto donde escuchará Nginx
EXPOSE 8080

# Inicia Nginx usando nuestra configuración
ENTRYPOINT ["nginx", "-c", "/etc/nginx/nginx.conf"]
CMD ["-g", "daemon off;"]