apiVersion: v1

# Crea una dirección estable para acceder a FastAPI
kind: Service

# Información que identifica al Service
metadata:
  name: api
  namespace: clinica-veterinaria

# Configuración del Service
spec:
  # Permite acceder a la API desde fuera del clúster de Minikube
  type: NodePort

  # Selecciona únicamente los Pods de la versión Blue
  selector:
    app: clinica-api
    version: blue

  # Puertos manejados por el Service
  ports:
    - name: http
      protocol: TCP

      # Puerto estable del Service dentro del cluster
      port: 8000

      # Nombre del puerto definido en el contenedor de FastAPI
      targetPort: http