apiVersion: v1

# Tipo Service
kind: Service

# Info que identifica al Service
metadata:
  name: frontend
  namespace: clinica-veterinaria

# Config del Service
spec:
  # Permite acceder al frontend desde fuera del cluster
  type: NodePort

  # Selecciona los Pods del frontend Blue
  selector:
    app: clinica-frontend
    version: blue

  # Puertos manejados por el Service
  ports:
    - name: http

      # Puerto del Service dentro del cluster
      port: 8080

      # Nombre del puerto declarado en el contenedor
      targetPort: http